name: Shorty API CI

on:
  push

jobs:
  build-api:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: pwd
    - run: ls -al
    - run: cd shorty_api
    - run: npm install -P
    - run: npm run ts:build
    - run: cd ..
    - run: docker build -t shorty-api -f Dockerfile_shorty-api .